import { defineCollection } from 'vuepress-theme-plume';

export default defineCollection({
	type: 'doc',
	title: 'DND-5R',
	linkPrefix: '/rule/dnd/',
	dir: 'rule/dnd',
	sidebar: [
		{
			text: '新手指南',
			icon: 'icon-park-twotone:guide-board',
			prefix: 'guide',
			collapsed: false,
			items: [
				'preparation',
				'character_creation',
				'quick_roll',
				'roleplay',
				'combat',
				'faq',
			],
		},
		{
			text: '资料信息',
			icon: 'icon-park-twotone:guide-board',
			collapsed: false,
			prefix: 'data',
			items: [
				{
					text: '职业',
					icon: 'ic:outline-hotel-class',
					prefix: 'class',
					collapsed: true,
					items: [
						'index',
						'barbarian',
						'rogue',
						'monk',
						'fighter',
						'ranger',
						'paladin',
						'cleric',
						'druid',
						'warlock',
						'bard',
						'sorcerer',
						'wizard',
						'artificer',
						'blood_hunter',
						'illrigger',
						'gunslinger',
					],
				},
				{
					text: '种族',
					icon: 'material-symbols-light:genetics-rounded',
					prefix: 'race',
					collapsed: true,
					items: ['index', 'dragon_born', 'furry', 'fairy'],
				},
				{
					text: '专长',
					icon: 'game-icons:fist',
					prefix: 'feat',
					collapsed: true,
					items: ['index', 'origin', 'general', 'fighting_style', 'epic_boon'],
				},
				'skill',
				'tool',
				{
					text: '法术',
					icon: 'game-icons:floating-crystal',
					prefix: 'spell',
					collapsed: true,
					items: [
						'index',
						'recommended',
						'lv_1',
						'lv_2',
						'lv_3',
						'lv_4',
						'lv_5',
						'lv_6',
						'lv_7',
						'lv_8',
						'lv_9',
					],
				},
				{
					text: '物品',
					icon: 'mdi:treasure-chest-outline',
					prefix: 'item',
					collapsed: true,
					items: [
						'index',
						'common',
						'uncommon',
						'rare',
						'very_rare',
						'legendary',
					],
				},
				'condition',
				'bastion',
			],
		},
		{
			text: '其他资料',
			icon: 'material-symbols:quick-reference-all',
			collapsed: false,
			prefix: 'ref',
			items: [
				{
					text: 'ACG 角色',
					icon: 'game-icons:crystal-wand',
					prefix: 'acg',
					collapsed: true,
					items: ['index', 'madoka_magica', '1999'],
				},
				{
					text: '神官 - 村规',
					icon: 'healthicons:village-24px',
					prefix: 'house_rule',
					collapsed: true,
					items: ['overall', 'tarrot', 'camp', 'dungeon_meshi', 'craft'],
				},
				{
					text: '神官 - DLC',
					icon: 'healthicons:village-24px',
					prefix: 'dlc',
					collapsed: true,
					items: ['index', 'kamen_rider'],
				},
			],
		},
	],
});
