import { defineCollection } from 'vuepress-theme-plume';

export default defineCollection({
	type: 'doc',
	title: 'DND-5R',
	linkPrefix: '/rule/dnd_5r/',
	dir: 'rule/dnd_5r',
	sidebar: [
		{
			text: '新手指南',
			icon: 'icon-park-twotone:guide-board',
			prefix: 'guide',
			collapsed: false,
			items: [
				'about',
				'character_creation',
				'quick_roll',
				'roleplay',
				'combat',
				'skill_and_tool',
				'environment_and_condition',
				'faq',
			],
		},
		{
			text: '简化资料',
			icon: 'prime:book',
			collapsed: false,
			prefix: 'brief_ref',
			items: [
				'class',
				'race',
				{
					text: '专长',
					icon: 'game-icons:fist',
					prefix: 'feat',
					collapsed: true,
					items: ['index', 'origin', 'general', 'fighting_style', 'epic_boon'],
				},
				'tool',
				{
					text: '法术',
					icon: 'game-icons:floating-crystal',
					prefix: 'spell',
					collapsed: true,
					items: [
						'index',
						'recommended',
						'lv_1',
						'lv_2',
						'lv_3',
						'lv_4',
						'lv_5',
						'lv_6',
						'lv_7',
						'lv_8',
						'lv_9',
					],
				},
				{
					text: '物品',
					icon: 'mdi:treasure-chest-outline',
					prefix: 'item',
					collapsed: true,
					items: [
						'index',
						'common',
						'uncommon',
						'rare',
						'very_rare',
						'legendary',
					],
				},
				'bastion',
			],
		},
		{
			text: '其他资料',
			icon: 'material-symbols:quick-reference-all',
			collapsed: false,
			prefix: 'ref',
			items: [
				{
					text: 'ACG 角色',
					icon: 'game-icons:crystal-wand',
					prefix: 'acg_character',
					collapsed: true,
					items: ['index', 'madoka_magica', '1999'],
				},
				{
					text: '神官 - 村规',
					icon: 'healthicons:village-24px',
					prefix: 'house_rule',
					collapsed: true,
					items: ['index', 'tarrot', 'camp', 'dungeon_meshi', 'craft'],
				},
				{
					text: '神官 - DLC',
					icon: 'healthicons:village-24px',
					prefix: 'dlc',
					collapsed: true,
					items: ['index', 'kamen_rider'],
				},
			],
		},
	],
});
